# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'instaClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  # Pods for instaClone
# add pods for desired Firebase products
pod 'Firebase/Firestore'
pod 'Firebase/Auth'

end
